---
name: Lint Code Base
on: push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.2.0

      - name: Lint Code Base
        uses: docker://github/super-linter:v5.0.0
        env:
          VALIDATE_ENV: false
